audit_header: false
title: St. Louis Real Estate Video Blog with John Sprague
description: Our mission at Onward Property Partners is to be your best resource for St. Louis real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Onward Property Partners, your professional St. Louis Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: John Sprague
  title:
  license_number:
  about_markdown: |
    We love helping buyers find their dream home! That's why we work with each client individually, taking the time to understand their unique lifestyles, needs and wishes.

    You'll find that we'll be a committed ally to negotiate on your behalf and with the backing of a trusted company. Get in touch with us today!
  brand: Onward Property Partners
  brokerage: KW Chesterfield - Keller Williams
  market: St. Louis
  address: '16690 Swingley Ridge Rd #240 Chesterfield , MO 63017'
  phone: 636-534-8335
  phone_type:
  phone2:
  phone2_type:
  email: john@onwardpropertypartners.com
  url: https://www.onwardpropertypartners.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.howmuchismystlhomeworth.info/
  second_CTA_text: KW App
  second_CTA_URL: https://app.kw.com/KW2N2CNRQ/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your St. Louis Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.howmuchismystlhomeworth.info/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/003.jpg
    CTA_title2: "Looking for your dream home?"
    CTA_text2: "Search the entire MLS for your St. Louis home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.onwardpropertypartners.com/search#?q_limit=36&mlsId=127&status=1|3&q_sort=createdAt-&q_offset=0

third_sidebar_CTA:
  - CTA_image_path3: /img/cta-images/002.jpg
    CTA_title3: "Searching for a St. Louis Home?"
    CTA_text3: "Get FREE instant access to local homes from any mobile device."
    CTA_link_text3: "Download my KW App"
    CTA_url3: https://app.kw.com/KW2N2CNRQ/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/OnwardPropertyPartnersInternational/
  linkedin_url:
  youtube_url: https://www.youtube.com/channel/UCgYW86fEZmqBtc5CvWFwC8A
  twitter_url: https://twitter.com/PartnersOnward
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'St. Louis Real Estate Podcast with John Sprague'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the St. Louis Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Onward Property Partners - your professional St. Louis Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in St. Louis, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'John Sprague'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: St. Louis Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#b40101'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
